### ISSUE TITLE
Valide ZIP-Files

### ISSUE THREAD

**Issue by u233336** [openTdataCH/OJP-Showcase#12]
Als PO will ich sicherstellen, dass die ZIP-Files valide / OK sind, damit die Datenabnehmer die ZIP-Files (automatisch) entpacken können.

**Akzeptanzkriterien**
- die auf der ODPCH publizierten ZIP-Files sind valide
- die auf der ODPCH publizierten ZIP-Files können entpackt werden
- bei einem invaliden / nicht entpackbaren ZIP-File wird der / die PO per Mail informiert

**Comment by vasile** [comment]
WIll be reported as an error by the HRDF importer anyway

**Comment by vasile** [comment]
Importer tool will report as a problem anyway from [tools/scripts/fetch-import-latest-hrdf.sh](https://github.com/openTdataCH/OJP-Showcase/blob/develop/tools/scripts/fetch-import-latest-hrdf.sh)
