### ISSUE TITLE
Create tool to import HRDF text files into DB

### ISSUE THREAD

**Issue by vasile** [openTdataCH/OJP-Showcase#13]
- schema to be defined
- for HRDF 5.40
- Python? (via Docker)
- SQLite as DB

**Comment by u233336** [comment]
If useful for you and the following work, the OK for me.

**Comment by ue71603** [comment]
Works for me. I think we will need an internal representation for some analysis and tools.

**Comment by vasile** [comment]
Added also Docker support, also updated documentation for `HRDF DB importer` in https://github.com/openTdataCH/OJP-Showcase/tree/develop/hrdf-tools => closing as **DONE**
