### ISSUE TITLE
Adds geo-enhacements support for the stops reporter tool

### ISSUE THREAD

**Issue by vasile** [openTdataCH/OJP-Showcase#15]
Follow-up from #3 
- implement flag for ch, non-ch stations as explained here: https://github.com/openTdataCH/OJP-Showcase/issues/3#issuecomment-757767841
- ~~experimental: do a spatial intersection with OSM data - see [comment 1](https://github.com/openTdataCH/OJP-Showcase/issues/3#issuecomment-759659646), [comment 2](https://github.com/openTdataCH/OJP-Showcase/issues/3#issuecomment-759989338)~~ done already by @haeckerbaer, see below

**Comment by haeckerbaer** [comment]
Hi @vasile 
I hope you're doing well?!
You can strike through the second point "spatial intersection" as I already experimented with it as describesd [in our Confluence](https://confluence.sbb.ch/pages/viewpage.action?pageId=1743296110#Aufwandsch%C3%A4tzungHaltestellenstrukturierung-PriorisierungaufBasisvonOpenStreetMapundsozialenEinrichtungen). I took an OSM pbf export of Switzerland, filtered it with Osmosis and then processed it with QGIS. Output is an excel sheet with all the DiDok stops that are near a social facility. I'm also experimenting with missing sidewalks and gaps in the OSM footway graph.
LG
Adrian

**Comment by vasile** [comment]
Hi @haeckerbaer - I've updated the issue, super that you've make progress!

**Comment by vasile** [comment]
Hi @haeckerbaer we are cleaning up the backlog, lets close this current ticket and reopen / open a new one if you need new features
