### ISSUE TITLE
Compare GTFS Static / RT

### ISSUE THREAD

**Issue by u233336** [openTdataCH/OJP-Showcase#18]
Missing number

**Comment by u233336** [comment]
![image](https://user-images.githubusercontent.com/74775157/132302029-f7a7c79b-8ead-4460-98bc-e0167210f0bc.png)

Shouldn't the number next to GTFS-RT show the amount of trips without RT-informatione? If yes, then there is something wrong because TPF alone has more missing RT-trips than shown in the top most line

**Comment by u233336** [comment]
After discussion with Vasile we realized, that the report has two sections

- Section 1: GTFS-RT data without static entries
- Section 2: GTFS static entries without real time data

It would be useful to have a summary over the section 2: how many entries in the GTFS static are missing GTFS-RT data?
![image](https://user-images.githubusercontent.com/74775157/132875368-6116fcdd-b325-4b5c-958d-4e84db06d89e.png)

**Comment by vasile** [comment]
Added headers and stats in the latest release
Check [apps/gtfs-rt-status/CHANGELOG.md](https://github.com/openTdataCH/OJP-Showcase/blob/develop/apps/gtfs-rt-status/CHANGELOG.md) for latest changes

![image](https://user-images.githubusercontent.com/113994/139602563-1ec216fc-d7b5-4681-aaee-2345c84d55da.png)
