### ISSUE TITLE
Aufschaltung der App/Features auf der ODPCH

### ISSUE THREAD

**Issue by rahelryf** [openTdataCH/OJP-Showcase#19]
Die Features und Apps, welche als Hilfe/Unterstützung für die Entwickler durch Vasile programmiert wurden, sollen nun auf der ODPCH zur Verfügung gestellt und beschrieben werden. 

Was wird benötigt:
- Cookbook Seite (wird erstellt durch Rahel)
- Beschrieb der App auf englisch inkl. Anleitung diese zu nutzen (Vasile)
- Deutsche Übersetzung (kann ich(Rahel) übernehmen)

**Comment by vasile** [comment]
Hi @rahelryf here is the current overview:

There are 2 main categories
- apps - web applications and APIs used by these
- tools - command line Python tools 
Each of the apps/tools below have individual `README` pages to know how to build / run them.

Apps
- [GTFS static - RT comparison web tool](https://github.com/openTdataCH/OJP-Showcase/tree/develop/apps/gtfs-rt-status) - you can read the actual process in the [GTFS-RT-static-comparison.md](https://github.com/openTdataCH/OJP-Showcase/blob/develop/apps/gtfs-rt-status/docs/GTFS-RT-static-comparison.md) document
- [GTFS-query](https://github.com/openTdataCH/OJP-Showcase/tree/develop/apps/gtfs-query) - this is an API that retrieves GTFS static related info for the GTFS static - RT comparison web tool above. 
- There is also the first version of the [OJP-demo](https://github.com/openTdataCH/OJP-Showcase/tree/develop/apps/ojp-demo) project which was replaced with the stand-alone [OJP-demo-app](https://github.com/openTdataCH/ojp-demo-app-src) repo. 

Tools
- [gtfs-prev-compare](https://github.com/openTdataCH/OJP-Showcase/tree/develop/tools/gtfs-prev-compare) - tool for comparison between 2 GTFS static datatsets - see [#5 gtfs2020-Vergleich](https://github.com/openTdataCH/OJP-Showcase/issues/5) for additional details
- [gtfs-rt-fetch](https://github.com/openTdataCH/OJP-Showcase/tree/develop/tools/gtfs-rt-fetch) - tool to fetch latest GTFS-RT JSON file
- [gtfs-static-db-importer](https://github.com/openTdataCH/OJP-Showcase/tree/develop/tools/gtfs-static-db-importer) - tool that imports a GTFS dataset into a SQLiteDB file.
- [gtfs-static-fetch-latest](https://github.com/openTdataCH/OJP-Showcase/tree/develop/tools/gtfs-static-fetch-latest) - tool that fetches and extracts the latest GTFS dataset from `api.opentransportdata.swiss` via the CKAN API.
- [gtfs-static-snapshot-exporter](https://github.com/openTdataCH/OJP-Showcase/tree/develop/tools/gtfs-static-snapshot-exporter) - this is a deprecated tool that was used to create the daily snapshots for the GTFS static - RT comparison web tool above.
- [hrdf-db-importer](https://github.com/openTdataCH/OJP-Showcase/tree/develop/tools/hrdf-db-importer) - tool that imports a HRDF dataset into a SQLiteDB file.
- [hrdf-stops-reporter](https://github.com/openTdataCH/OJP-Showcase/tree/develop/tools/hrdf-stops-reporter) - tool that generates a CSV report with information for each station. See [#3 Small statistics for an analysis of stops](https://github.com/openTdataCH/OJP-Showcase/issues/3) to have an idea what is inside the CSV. Sample output Excel files are stored in [assets-hrdf-stops-reporter](https://github.com/openTdataCH/assets-hrdf-stops-reporter) repo.
