### ISSUE TITLE
Add GUI for the comparison tools

### ISSUE THREAD

**Issue by u233336** [openTdataCH/OJP-Showcase#20]
Als PO ODPCH / PO OJP
will ich den die Vergleiche der gtfs2020- und HRDF-Datenexport mit mit einem GUI bedienen können,
damit ich die Vergleiche bequem anstellen kann.

Akzeptanzkriterien:
Die Codes der folgenden beiden Issues können mit einem GUI bedient werden:

- https://github.com/openTdataCH/OJP-Showcase/issues/6
- https://github.com/openTdataCH/OJP-Showcase/issues/5
(später auch https://github.com/openTdataCH/OJP-Showcase/issues/7)

Die folgenden Elemente sind auf dem GUI vorhanden:
- Radiobutton zur Art des Vergleichs (gtfs2gtfs, hrdf2hrdf, hrds2gtfs)
- File-Picker für File 1 (zu vergleichende Datei)
- File-Picker für File 2 (Referenzdatei, zu welcher verglichen wird)
- Übersicht der Resultate als Zusammenfassung
- übersichtliche Darstellung der Details (tbd)

**Comment by vasile** [comment]
Closing it now and @u233336 can reopen for indvidual apps or tools from https://github.com/openTdataCH/OJP-Showcase
