### ISSUE TITLE
Migrate Tools on Mentz Server

### ISSUE THREAD

**Issue by u233336** [openTdataCH/OJP-Showcase#22]
As product owner I need the developped tools on the new server with Mentz
so that the tools are accessible for all the users in charge - even when Vasiles server should be down.

**Comment by vasile** [comment]
The tools are now available in the new server
- cronjobs for importing HRDF and GTFS are set, @u233336 is in the `MAILTO`
- the tools are running now here:
  - https://tools.odpch.ch/gtfs-rt-status/
  - https://tools.odpch.ch/hrdf-check-duplicates/
