### ISSUE TITLE
Small statistics for an analysis of stops

### ISSUE THREAD

**Issue by ue71603** [openTdataCH/OJP-Showcase#3]
We would like to have a table of all stops with their characteristics. this will be used for an analysis of accessibility demands.

Important parts are (in German):
Pro Haltestelle welche 

- TU sind zuständig? => Abgeleitet aus FPLAN Einträgen (zweite Spalte der *Z Zeile) und UMSTEIGV Einträgen 
- Wie viele Linien pro Haltestelle? => Abgeleitet aus FPLAN Einträgen (jeweils die erste Spalte der *G und *L Zeile und der Betreiber)
- Wie viele Angebotskategorien? => Abgeleitet aus FPLAN Einträgen (erste Spalte der *G Zeile)
- Wie viele Steige hat eine Haltestelle? => Abgeleitet aus GLEIS Einträgen
- Wie viele Umsteigebeziehungen hat eine Haltestelle? => Abgeleitet aus METABHF, UMSTEIGL und UMSTEIGZ Einträgen

Definitionen von mir (alles ohne führende Nullen):
•	Haltestelle = 85+<DiDok-Nr.>, so wie sie in HRDF vorhanden sind. Beispiel «8503000»
•	Gleis/Steig/Haltekante = <G-Spalte>+<A-Spalte> aus GLEIS Einträgen, also z.B. 11C (dazugehöriger GLEIS Einträg wäre «8515296 #0000002 G '11' A 'C'»
•	TU/Transportunternehmen = <K-Spalte> aus BETRIEB Einträgen, also z.B. «SVB» und zweite Spalte in *Z Zeile aus FPLAN Eintrag, also z.B. «834» (dazugehörige *Z Zeile wäre «*Z 066162 000834   001»
•	Angebotskategorie = <Erste Spalte der *G Zeile aus FPLAN Eintrag>, also z.B. «B» (dazugehörige *G Zeile wäre «*G B   8589150 8592375  01030  01053»
•	Linie = <Erste Spalte der *G Zeile aus FPLAN Eintrag>+<Erste Spalte der *L Zeile aus FPLAN Eintrag> und TU, also z.B. B12 (834) für Buslinie 12 von Betreiber 834

The result should be an Excel table that looks like this
![image](https://user-images.githubusercontent.com/24227470/101767320-53ee1b00-3ae4-11eb-87ee-9d39d3a699dc.png)

The base should be HRDF or GTFS, whatever suits more.
If possible we would like to have a script (e.g. python)    stopcomplexity.py --inputfile <file> --outputfile <file>

**Comment by ue71603** [comment]
@haeckerbaer

**Comment by vasile** [comment]
Depends on #13

**Comment by Richardanielutz** [comment]
•	HRDF version is 5.40, right?
--> right!

**Comment by Richardanielutz** [comment]
Also if you run the tool in summer 2021 lets say, we can add another filter, to discard FPLAN entries that have a BITFELD entry in the past (i.e. it was used only in Winter).
--> A filter with the designation "from <date> ... to <date>" would be great

**Comment by haeckerbaer** [comment]
Hi Vasile,
Thanks for your work so far!
I discussed it with Rich and it would be great if you could extend it by the following columns:
![image](https://user-images.githubusercontent.com/54021300/103770203-eae7bd80-5025-11eb-9b49-74aa0fb160ce.png)
- a column "Anzahl VM-Kategorien" with the number of different transport categories (rail, bus, tram etc.) that operate at said stop.
- a column "VM-Kategorien" with the different transport categories (rail, bus, tram etc.) that operate at said stop.
- a column "Anzahl Aufrüfe als Zwischenhalt" that corresonds to the number of times that this stop is "called" as an intermediate stop in a journey pattern (not the first or last stop).
- a column "Anzahl Aufrüfe als Starthalt" that corresonds to the number of times that this stop is "called" as the origin / first stop in a journey pattern.
- a column "Anzahl Aufrüfe  als Endhalt" that corresonds to the number of times that this stop is "called" as the destination / last stop in a journey pattern.
You find attached a list for the mapping of the Angebotskategorien (FPLAN file, first column of the *G row) to the "Verkehrsmittelkategorie":
[Mapping_Angebotskategorie_Verkehrsmittelkategorie.xlsx](https://github.com/openTdataCH/OJP-Showcase/files/5775818/Mapping_Angebotskategorie_Verkehrsmittelkategorie.xlsx)
We are also open for suggestions from you! Do you have other ideas of how to classify the stops according to size, complexity, interchange priority and so on? Unfortunately INFO+ has insufficient or even flawed information in UMSTEIG, METABHF and BFPRIOS. The line and "Angebotskategorie" data is helpful but there are >2000 cases where such information is missing, so we need some other feature:
![image](https://user-images.githubusercontent.com/54021300/103774582-1ae68f00-502d-11eb-9bed-11a1f8b66ca4.png)
Thanks in advance and a happy new year / good start into 2021!
Cheers, 
Adrian

**Comment by vasile** [comment]
Hi @haeckerbaer , I've added also these fields, the Excel files are now available in [hrdf-tools/export/stops_reporter](https://github.com/openTdataCH/OJP-Showcase/tree/develop/hrdf-tools/export/stops_reporter). 

BTW, I've tried to run them with the latest HRDF dataset but it seems that [Dec, 20 2020](https://opentransportdata.swiss/de/dataset/timetable-54-2021-hrdf) is the last one? /cc @ue71603 @Richardanielutz 

Just a small note, the first/middle/last stops counting might reflect the wrong for LB, GB, FUN (aerialway, funicular service types, etc) which are represented in FPLAN with a frequency number, i.e. one FPLAN entry describes a full day of operations with a given frequency.
![image](https://user-images.githubusercontent.com/113994/103906831-bac11d00-5100-11eb-9ed5-1245d67e0850.png)

With regard of classification suggestions, lets chat and iterate on some ideas, I'm missing for sure a geo-representation of the dataset, I would start by removing all the noise, i.e. when visualizing the Excel on the map, I can see that more than 2'000 stops are outside of Switzerland (not on the border service, they are just completely outside).
![image](https://user-images.githubusercontent.com/113994/103907590-bf3a0580-5101-11eb-87f7-bb03056fed46.png)

Initially there were only few of them in Germany, now they are also appearing in France. What I can do is to add a buffer around the swiss borders (lets say x kilometers) and flag everything that is outside(new column). Anyway lets chat on our next sync.

**Comment by haeckerbaer** [comment]
Hi @vasile 
Thanks for the update! 
"I can see that more than 2'000 stops are outside of Switzerland": 
Rich already filtered the data according to the following rule:
- stop places with a DiDok number 0-999'999 => special "virtual" stops (in switzerland); we call them "mobility hubs" (also relevant for us)
- stop places with a DiDok number 1'000'000 => foreign stops (can be filtered out)
- stop places with a DiDok number 85xxxxx => swiss stops (the ones that are relevant for us)
- stop places with a DiDok number from 8600000 on => foreign stops (can be filtered out)

A buffer might make more sense but we have to discuss it with Rich.
Not so sure what to do with the frequency based ones.. We can also discuss it with Rich. We have a meeting tomorrow 9-10am, are you available then, by any chance?
Cheers

**Comment by vasile** [comment]
> Rich already filtered the data according to the following rule:

Nice, I can also implement this rule in the parser. 

> A buffer might make more sense but we have to discuss it with Rich.
> Not so sure what to do with the frequency based ones.. We can also discuss it with Rich. We have a meeting tomorrow 9-10am, are you available then, by any chance?

I'll try to dial-in, lets chat on email, please send me an email invite

**Comment by haeckerbaer** [comment]
Hi @vasile 
Rich and I discussed another interesting option to get a more meaningful characterization/priorization of the stops in terms of accessiblity:
a GiS mapping with accessibility relevant POIs like nursing_home, hospital and other social_facility amenities from OpenStreetMap. Could you extract such data from OpenStreetMap or maybe heiminfo.ch and add a buffer around the nodes/ways (e.g. 100 meters or simply the "nearest" hrdf stop) and flag every hrdf stop that is inside? We would first need to define exactly what OSM tags we want to filter though. @Richardanielutz will discuss it further with you. Other POI suggestions welcome! I also discussed it with the SBB Routing and Map Service (ROKAS) and they will provide us with further data to help with the priorization (although I don't know yet how this data will look like or in what form they will provide it..).

Another point is the filtering of swiss/foreign stops according to the rules provided above (if you didn't already update the parser).
Cheers,
Adian

**Comment by Richardanielutz** [comment]
Hi @vasile and @haeckerbaer 
I have tried to collect a list of all possible OSM-tags of the relevant POIs:

- amenity=clinic
- amenity=hospital
- amenity=nursing_home
- amenity=social_facility --> If possible, consider here what kind of social_facility
- social_facility=group_home
- social_facility=nursing_home
- social_facility=assisted_living
- social_facility=day_care
- social_facility=workshop
- social_facility:for=disabled
- social_facility:for=diseased
- social_facility:for=mental_health
- social_facility:for=senior

It would be great if the OSM tags assigned to each stop were included. We can discuss this briefly in our meeting.
CU
rich

**Comment by vasile** [comment]
As decided on 14.01 - I'll develop the OSM-features in #15 and close the current issue. 
The `stops_reporter_cli.py` tool is dockerized and documented in https://github.com/openTdataCH/OJP-Showcase/tree/develop/hrdf-tools.
