### ISSUE TITLE
gtfs-Vergleich

### ISSUE THREAD

**Issue by u233336** [openTdataCH/OJP-Showcase#4]
Als PO ODPCH / PO OJP
will ich den auf der ODPCH bereitgestellten gtfs-Datenexport mit dem Datenexport der Vorwoche vergleichen,
damit ich sicherstellen kann, dass der Umfang der exportierten Daten korrekt ist bzw. die gleiche Grössenordnung wie in der Vorwoche aufweist.

**Akzeptanzkriterien**:
Die folgenden Files der Datenlieferung werden über die ID mit der Datenlieferung der Vorwoche verglichen:
o	ageny.txt --> welche TU kommt hinzu / fehlt?
o	routes.txt --> welche Routen sind neu / fehlen?
o	stops.txt --> welche Haltestellen sind neu / fehlen?
o	transfers.txt --> welche Transfers sind neu / fehlen?

Für die folgenden Files wird die Anzahl Zeilen in den entsprechenden Files der Vorwoche verglichen:
o	calendar.txt
o	calendar-dates.txt
o	trips.txt

Die Resultate der Vergleiche wird in einem Dashboard / Email visualisiert.

**Comment by ue71603** [comment]
Der GTFS-Export wird auf Fahrplanwechsel eingestellt. Den können wir also sein lassen.
