### ISSUE TITLE
gtfs2020-Vergleich

### ISSUE THREAD

**Issue by u233336** [openTdataCH/OJP-Showcase#5]
Als PO ODPCH / PO OJP
will ich den auf der ODPCH bereitgestellten gtfs2020-Datenexport mit dem Datenexport der Vorwoche vergleichen,
damit ich sicherstellen kann, dass der Umfang der exportierten Daten korrekt ist bzw. die gleiche Grössenordnung wie in der Vorwoche aufweist.

**Akzeptanzkriterien**:
Die folgenden Files der Datenlieferung werden über die ID mit der Datenlieferung der Vorwoche verglichen:
o	ageny.txt --> welche TU kommt hinzu / fehlt?
o	routes.txt --> welche Routen sind neu / fehlen?
o	stops.txt --> welche Haltestellen sind neu / fehlen?
o	transfers.txt --> welche Transfers sind neu / fehlen?

Für die folgenden Files wird die Anzahl Zeilen in den entsprechenden Files der Vorwoche verglichen:
o	calendar.txt
o	calendar-dates.txt
o	trips.txt

Die Resultate der Vergleiche wird in einem Dashboard / Email visualisiert.

**Comment by vasile** [comment]
Created https://github.com/openTdataCH/OJP-Showcase/tree/develop/tools/gtfs-prev-compare
