### ISSUE TITLE
HRDF Vergleich

### ISSUE THREAD

**Issue by u233336** [openTdataCH/OJP-Showcase#6]
Als PO ODPCH / PO OJP
will ich den auf der ODPCH bereitgestellten HRDF-Datenexport mit dem Datenexport der Vorwoche vergleichen,
damit ich sicherstellen kann, dass der Umfang der exportierten Daten korrekt ist bzw. die gleiche Grössenordnung wie in der Vorwoche aufweist.

**Akzeptanzkriterien:**

- Wo möglich werden die Files der Datenlieferung über eine ID mit der Datenlieferung der Vorwoche verglichen
- Wo nicht über eine ID möglich, Für werden die Files über die Anzahl Zeilen mit den entsprechenden Files der Vorwoche verglichen
- Die Resultate der Vergleiche wird in einem Dashboard / Email visualisiert.

**Comment by vasile** [comment]
Closing as duplicate with #2
