### ISSUE TITLE
Prüfung auf doppelte Fahrten

### ISSUE THREAD

**Issue by u233336** [openTdataCH/OJP-Showcase#8]
Als PO ODPCH / PO OJP
will ich den auf der ODPCH bereitgestellten gtfs(2020)- und HRDF-Datenexport auf doppelte Fahrten prüfen,
damit ich sicherstellen kann, dass jede Fahrt genau ein einziges Mal publiziert wird.

**Akzeptanzkriterien**:
-	Es ist sichergestellt, dass jede Fahrt nur ein einziges Mal im Datenexport vorhanden ist.
-	Allfällige doppelte Fahrten werden in einer geeigneten Form auf einem Dashboard / Email gekennzeichnet.

**Comment by vasile** [comment]
@u233336 - please add the definition of "doppelte Fahrten"
- different trip_ids
- same arrival/departure time
- same service_id (bitfeld)

**Comment by u233336** [comment]
For the HRDF File:
The Z-line alone doesn't have to be unique
- especially for the operator Postauto this is not the case → for PAG the I RN line has to be added
- the combination Z-line + I RN-line must also be unique for PAG.
- for all other operators, however, the Z-line should be unique

**Comment by u233336** [comment]
Answer from my colleagues from INFO
[Unique_Fahrtnummer.pdf](https://github.com/openTdataCH/OJP-Showcase/files/8198926/Unique_Fahrtnummer.pdf)
+

**Comment by vasile** [comment]
Added 
- backend reports generator tool - [tools/hrdf-check-duplicates](https://github.com/openTdataCH/OJP-Showcase/tree/develop/tools/hrdf-check-duplicates) 
- frontend GUI - [apps/hrdf-check-duplicates](https://github.com/openTdataCH/OJP-Showcase/tree/develop/apps/hrdf-check-duplicates)
- deployed under https://tools.odpch.ch/hrdf-check-duplicates/
