### ISSUE TITLE
Abgleich gtfs2020 mit gtfsrt2020

### ISSUE THREAD

**Issue by ue71603** [openTdataCH/OJP-Showcase#9]
Als PO möchte ich sehen, welche Fahrten Echtzeit haben und welche nicht.

Akzeptanzkriterien:
* Lade eine gtfs2020 Static-Datei
* Extrahiere alle Fahrten mit dem heutigen Betriebstag für die im Moment Echtzeit vorhanden sein müsste. (Aktuelle Zeit - 30 Minuten bis Aktuelle Zeit 3h). Bereits aktive Fahrten müssten auch Echtzeit haben.
* Liste alle Fahrten mit Details, für die keine Echtzeit kommt. Die Liste enhält Betreiber (so dass damit gefiltert werden kann).
* Liste alle Fahrten auf, für die Echtzeit kommt, aber keine Fahrplanfahrt vorhanden war (einerseits Extrafahrten, andererseits Problemfälle).
* Liste alle Fahrten auf, für die ein Ausfall gemeldet wurde
* Liste alle Fahrten auf, für die Ein Teilausfall gemeldet wurde.
* Intermediary step: SQLIte DB with the GTFS tables

Input: local path to unzipped GTFS folder

Output format:
* TXT (default), JSON (with parameter)

**Comment by ue71603** [comment]
* In the logs: Where is the description of what the log represents. E.g. the 1300 and 1400 are not self-evident.
* Historical data is not available from the server. You would need to to fetch it regularly yourself.
* j21-ojp: is on Christoph's worklist
* operators without real-time: It would be great to be able to provide a list of operators to be excluded from analysis (as they never will have real-time as long as that is not set up. In prinicple the data is here: https://opentransportdata.swiss/de/dataset/go-realtime. If it can be directly used by you, that you have to decide.
*  Will you use: https://www.w3.org/TR/tabular-data-primer/

**Comment by vasile** [comment]
Add filters to ignore the Bergbahnen / TUs - from params or external file

**Comment by vasile** [comment]
Created `apps/gtfs-rt-status` webapp
https://github.com/openTdataCH/OJP-Showcase/tree/develop/apps/gtfs-rt-status

The workflow is documented here
https://github.com/openTdataCH/OJP-Showcase/blob/develop/apps/gtfs-rt-status/docs/GTFS-RT-static-comparison.md
